# Volume sizes for different data directories
volumes:
  movies:
    size: "50Gi"  # Size of the movies volume
    path: "/mnt/data/movies"
  tv:
    size: "100Gi"  # Size of the TV shows volume
    path: "/mnt/data/tv"
  config:
    size: "10Gi"  # Size of the config volume
    path: "/mnt/data/config"

service:
  type: NodePort
  port: 32400
  nodePort: 30001

plex:
  version: "1.40.2.8395-c67dce28e"