# Volume sizes for different data directories
volumes:
  movies:
    size: "100Gi"  # Size of the movies volume
    path: "/mnt/data/movies"
  tv:
    size: "100Gi"  # Size of the TV shows volume
    path: "/mnt/data/tv"
  config:
    size: "10Gi"  # Size of the config volume
    path: "/mnt/data/config"
  torrent:
    size: "50Gi"
    path: "/mnt/data/torrents"

plex:
  version: "1.40.2.8395-c67dce28e"

radarr:
  version: "5.6.0.8846-ls222"

sonarr:
  version: "4.0.5.1710-ls241"

qbittorrent:
  version: "4.6.5"