apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-sonarr
  labels:
    app: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
        - name: sonarr
          image: linuxserver/sonarr:{{ .Values.sonarr.version }}
          ports:
            - containerPort: 8989
              name: sonarr
          volumeMounts:
            - name: config
              mountPath: /config
            - name: tv
              mountPath: /data/media/tv
            - name: torrents-tv
              mountPath: /data/torrents/tv
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: sonarr-config-pvc
        - name: tv
          persistentVolumeClaim:
            claimName: sonarr-tv-pvc
        - name: torrents-tv
          persistentVolumeClaim:
            claimName: sonarr-torrent-tv-pvc

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-radarr
  labels:
    app: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          image: linuxserver/radarr:{{ .Values.radarr.version }}
          ports:
            - containerPort: 7878
              name: radarr
          volumeMounts:
            - name: config
              mountPath: /config
            - name: movies
              mountPath: /data/media/movies
            - name: torrents-movies
              mountPath: /data/torrents/movies
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: radarr-config-pvc
        - name: movies
          persistentVolumeClaim:
            claimName: radarr-movies-pvc
        - name: torrents-movies
          persistentVolumeClaim:
            claimName: radarr-torrent-movies-pvc