#TODO FIX TORRENTS VOLUME, MAKE MOUNT PATHS FOR VOLUMES


apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-sonarr
  labels:
    app: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
        - name: sonarr
          image: linuxserver/sonarr:{{ .Values.sonarr.version }}"
          ports:
            - containerPort: 8989
              name: sonarr
          volumeMounts:
            - name: config
              mountPath:
            - name: tv
              mountPath:
            - name: torrents
              mountPath:
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: sonarr-config-pvc
        - name: tv
          persistentVolumeClaim:
            claimName: sonarr-tv-pvc
        - name: torrents
          persistentVolumeClaim:
            claimName:

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-radarr
  labels:
    app: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          image: "linuxserver/radarr:{{ .Values.radarr.version }}"
          ports:
            - containerPort: 7878
              name: radarr
          volumeMounts:
            - name: config
              mountPath:
            - name: movies
              mountPath:
            - name: torrents
              mountPath:
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: radarr-config-pvc
        - name: movies
          persistentVolumeClaim:
            claimName: radarr-movies-pvc
        - name: torrents
          persistentVolumeClaim:
            claimName: