{{- if .Values.overseerr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: overseerr
  labels:
    app: overseerr
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5055
      targetPort: 5055
      nodePort: {{ .Values.overseerr.nodeport }}
  selector:
    app: overseerr

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseerr
  labels:
    app: overseerr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: overseerr
  template:
    metadata:
      labels:
        app: overseerr
    spec:
      containers:
        - name: overseerr
          image: linuxserver/overseerr:{{ .Values.overseerr.version }}
          ports:
            - containerPort: 5055
              name: overseerr
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: overseerr-config-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr-config-pvc
spec:
  accessModes:
    - ReadWriteOnce #only one pod has R/W on its conf
  resources:
    requests:
      storage: {{ .Values.volumes.config.size }}
  storageClassName: local-path 
  volumeName: overseerr-config-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: overseerr-config-pv
spec:
  capacity:
    storage: {{ .Values.volumes.config.size }}
  storageClassName: local-path 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.volumes.config.path }}/overseerr

{{- end }}