apiVersion: v1
kind: Service
metadata:
  name: plex
  labels:
    app: plex
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 32400 # Service port
      targetPort: 32400 # Container port
      nodePort: {{ .Values.plex.nodeport }}
  selector:
    app: plex

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  labels:
    app: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
      # annotations:
      #   k8s.v1.cni.cncf.io/networks: wifi-net #see plex-wifi.yaml
    spec:
      containers:
        - name: plex
          image: plexinc/pms-docker:{{ .Values.plex.version }}  # Plex Docker image
          ports:
            - containerPort: 32400
              name: plex
          volumeMounts:
            - name: media
              mountPath: /data/media/ # Mount path for media
            - name: config-storage
              mountPath: /config  # Mount path for config
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: plex-media-pvc  # PVC for media
        - name: config-storage
          persistentVolumeClaim:
            claimName: plex-config-pvc  # PVC for config


###### PV
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media-pv
spec:
  capacity:
    storage: {{ .Values.volumes.media.size }}
  storageClassName: local-path 
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.volumes.media.path}}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config-pv
spec:
  capacity:
    storage: {{ .Values.volumes.config.size }}
  storageClassName: local-path 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.volumes.config.path }}/plex

##### PVC
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-pvc
spec:
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: {{ .Values.volumes.media.size }}
  storageClassName: local-path 
  volumeName: plex-media-pv

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-pvc
spec:
  accessModes:
    - ReadWriteOnce #only one pod has R/W on its conf
  resources:
    requests:
      storage: {{ .Values.volumes.config.size }}
  storageClassName: local-path 
  volumeName: plex-config-pv