apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  labels:
    app: qbittorrent
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: {{ .Values.qbittorrent.nodeport }}
  selector:
    app: qbittorrent

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  labels:
    app: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
        - name: qbittorrent
          image: linuxserver/qbittorrent:{{ .Values.qbittorrent.version }}
          ports:
            - containerPort: 8080
              name: qbittorrent
          volumeMounts:
            - name: config
              mountPath: /config
            - name: movies
              mountPath: /data/media/radarr
            - name: tv
              mountPath: /data/media/tv-sonarr
            - name: torrents
              mountPath: /data/torrents/
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: torrent-config-pvc
        - name: torrents
          persistentVolumeClaim:
            claimName: torrent-pvc
        - name: movies
          persistentVolumeClaim:
            claimName: qb-movies-pvc
        - name: tv
          persistentVolumeClaim:
            claimName: qb-tv-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torrent-config-pvc
spec:
  accessModes:
    - ReadWriteOnce #only 1 pod has R/W on its conf
  resources:
    requests:
      storage: {{ .Values.volumes.config.size }}
  storageClassName: local-path 
  volumeName: torrent-config-pv


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: torrent-config-pv
spec:
  capacity:
    storage: {{ .Values.volumes.config.size }}
  storageClassName: local-path 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.volumes.config.path }}/torrent

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torrent-pvc
spec:
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: {{ .Values.volumes.torrent.size }}
  storageClassName: local-path 
  volumeName: torrent-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: torrent-pv
spec:
  capacity:
    storage: {{ .Values.volumes.torrent.size }}
  storageClassName: local-path 
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.volumes.torrent.path }}


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qb-movies-pvc
spec:
  accessModes:
    - ReadWriteMany #plex pvc read only on media
  resources:
    requests:
      storage: {{ .Values.volumes.media.size }}
  storageClassName: local-path 
  volumeName: qb-movies-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qb-movies-pv
spec:
  capacity:
    storage: {{ .Values.volumes.media.size }}
  storageClassName: local-path 
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.volumes.media.path}}/movies

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qb-tv-pvc
spec:
  accessModes:
    - ReadWriteMany #plex pvc read only on media
  resources:
    requests:
      storage: {{ .Values.volumes.media.size }}
  storageClassName: local-path 
  volumeName: qb-tv-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qb-tv-pv
spec:
  capacity:
    storage: {{ .Values.volumes.media.size }}
  storageClassName: local-path 
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.volumes.media.path}}/tv