apiVersion: v1
kind: Service
metadata:
  name: radarr
  labels:
    app: radarr
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 7878
      targetPort: 7878
      nodePort: {{ .Values.radarr.nodeport }}
  selector:
    app: radarr

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  labels:
    app: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          image: linuxserver/radarr:{{ .Values.radarr.version }}
          ports:
            - containerPort: 7878
              name: radarr
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /data/media/
            - name: torrents
              mountPath: /data/downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: radarr-config-pvc
        - name: media
          persistentVolumeClaim:
            claimName: radarr-movies-pvc
        - name: torrents
          persistentVolumeClaim:
            claimName: radarr-torrent-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-pvc
spec:
  accessModes:
    - ReadWriteOnce #only one pod has R/W on its conf
  resources:
    requests:
      storage: {{ .Values.volumes.config.size }}
  storageClassName: local-path 
  volumeName: radarr-config-pv



---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-torrent-pvc
spec:
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: {{ .Values.volumes.torrent.size }}
  storageClassName: local-path 
  volumeName: radarr-torrent-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-config-pv
spec:
  capacity:
    storage: {{ .Values.volumes.config.size }}
  storageClassName: local-path 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.volumes.config.path }}/radarr


---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-torrent-pv
spec:
  capacity:
    storage: {{ .Values.volumes.torrent.size }}
  storageClassName: local-path 
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.volumes.torrent.path }}

---



apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-movies-pv
spec:
  capacity:
    storage: {{ .Values.volumes.media.size }}
  storageClassName: local-path 
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.volumes.media.path}}/movies

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-movies-pvc
spec:
  accessModes:
    - ReadWriteMany #plex pvc read only on media
  resources:
    requests:
      storage: {{ .Values.volumes.media.size }}
  storageClassName: local-path 
  volumeName: radarr-movies-pv