apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-plex
  labels:
    app: plex
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 32400 # Service port
      targetPort: 32400 # Container port
      nodePort: 32400
  selector:
    app: plex

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sonarr
  labels:
    app: sonarr
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8989
      targetPort: 8989
      nodePort: 32500
  selector:
    app: sonarr

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-radarr
  labels:
    app: radarr
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 7878
      targetPort: 7878
      nodePort: 32600
  selector:
    app: radarr