# nodePort gotta be between 30000 and 32700
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-plex
  labels:
    app: plex
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 32400 # Service port
      targetPort: 32400 # Container port
      nodePort: {{ .Values.plex.nodeport }}
  selector:
    app: plex

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sonarr
  labels:
    app: sonarr
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8989
      targetPort: 8989
      nodePort: {{ .Values.sonarr.nodeport }}
  selector:
    app: sonarr

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-radarr
  labels:
    app: radarr
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 7878
      targetPort: 7878
      nodePort: {{ .Values.radarr.nodeport }}
  selector:
    app: radarr

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-qbittorrent
  labels:
    app: qbittorrent
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: {{ .Values.qbittorrent.nodeport }}
  selector:
    app: qbittorrent