apiVersion: v1
kind: Service
metadata:
  name: sonarr
  labels:
    app: sonarr
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8989
      targetPort: 8989
      nodePort: {{ .Values.sonarr.nodeport }}
  selector:
    app: sonarr

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  labels:
    app: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
        - name: sonarr
          image: linuxserver/sonarr:{{ .Values.sonarr.version }}
          ports:
            - containerPort: 8989
              name: sonarr
          volumeMounts:
            - name: config
              mountPath: /config
            - name: tv
              mountPath: /data/media/tv
            - name: torrents
              mountPath: /data/torrents
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: sonarr-config-pvc
        - name: tv
          persistentVolumeClaim:
            claimName: sonarr-tv-pvc
        - name: torrents
          persistentVolumeClaim:
            claimName: sonarr-torrent-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-pvc
spec:
  accessModes:
    - ReadWriteOnce #only one pod has R/W on its conf
  resources:
    requests:
      storage: {{ .Values.volumes.config.size }}
  storageClassName: local-path 
  volumeName: sonarr-config-pv



---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-torrent-pvc
spec:
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: {{ .Values.volumes.torrent.size }}
  storageClassName: local-path 
  volumeName: sonarr-torrent-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-config-pv
spec:
  capacity:
    storage: {{ .Values.volumes.config.size }}
  storageClassName: local-path 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.volumes.config.path }}/sonarr

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-torrent-pv
spec:
  capacity:
    storage: {{ .Values.volumes.torrent.size }}
  storageClassName: local-path 
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.volumes.torrent.path }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-tv-pvc
spec:
  accessModes:
    - ReadWriteMany #plex pvc read only on media
  resources:
    requests:
      storage: {{ .Values.volumes.media.size }}
  storageClassName: local-path 
  volumeName: sonarr-tv-pv

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-tv-pv
spec:
  capacity:
    storage: {{ .Values.volumes.media.size }}
  storageClassName: local-path 
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.volumes.media.path}}/tv