#####################################################
### CONFIG

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-pvc
spec:
  accessModes:
    - ReadWriteOnce #only one pod has R/W on its conf
  resources:
    requests:
      storage: {{ .Values.volumes.config.size }}
  storageClassName: local-path 
  volumeName: plex-config-pv

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-pvc
spec:
  accessModes:
    - ReadWriteOnce #only one pod has R/W on its conf
  resources:
    requests:
      storage: {{ .Values.volumes.config.size }}
  storageClassName: local-path 
  volumeName: radarr-config-pv

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-pvc
spec:
  accessModes:
    - ReadWriteOnce #only one pod has R/W on its conf
  resources:
    requests:
      storage: {{ .Values.volumes.config.size }}
  storageClassName: local-path 
  volumeName: sonarr-config-pv

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torrent-config-pvc
spec:
  accessModes:
    - ReadWriteOnce #only 1 pod has R/W on its conf
  resources:
    requests:
      storage: {{ .Values.volumes.config.size }}
  storageClassName: local-path 
  volumeName: torrent-config-pv

---

#####################################################
### PLEX MEDIA
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-movies-pvc
spec:
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: {{ .Values.volumes.movies.size }}
  storageClassName: local-path 
  volumeName: plex-movies-pv

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-tv-pvc
spec:
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: {{ .Values.volumes.tv.size }}
  storageClassName: local-path 
  volumeName: plex-tv-pv

---

#####################################################
### SONARR MEDIA

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-tv-pvc
spec:
  accessModes:
    - ReadWriteMany #plex pvc read only on media
  resources:
    requests:
      storage: {{ .Values.volumes.tv.size }}
  storageClassName: local-path 
  volumeName: sonarr-tv-pv

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-torrent-tv-pvc
spec:
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: {{ .Values.volumes.torrent.size }}
  storageClassName: local-path 
  volumeName: sonarr-torrent-tv-pv

---

#####################################################
### RADARR

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-movies-pvc
spec:
  accessModes:
    - ReadWriteMany #plex pvc read only on media
  resources:
    requests:
      storage: {{ .Values.volumes.movies.size }}
  storageClassName: local-path 
  volumeName: radarr-movies-pv

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-torrent-movies-pvc
spec:
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: {{ .Values.volumes.torrent.size }}
  storageClassName: local-path 
  volumeName: radarr-torrent-movies-pv

---

#####################################################
### QBITTORRENT

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torrent-movies-pvc
spec:
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: {{ .Values.volumes.torrent.size }}
  storageClassName: local-path 
  volumeName: torrent-movies-pv

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torrent-tv-pvc
spec:
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: {{ .Values.volumes.torrent.size }}
  storageClassName: local-path 
  volumeName: torrent-tv-pv

---