#####################################################
### MEDIA
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-movies-pv
spec:
  capacity:
    storage: {{ .Values.volumes.movies.size }}
  storageClassName: local-path 
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.volumes.movies.path}}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-tv-pv
spec:
  capacity:
    storage: {{ .Values.volumes.tv.size }}
  storageClassName: local-path 
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.volumes.tv.path}}

---
#### RADARR

apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-movies-pv
spec:
  capacity:
    storage: {{ .Values.volumes.movies.size }}
  storageClassName: local-path 
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.volumes.movies.path}}

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-torrent-movies-pv
spec:
  capacity:
    storage: {{ .Values.volumes.torrent.size }}
  storageClassName: local-path 
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.volumes.torrent.path }}/movies

---
#### SONARR

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-tv-pv
spec:
  capacity:
    storage: {{ .Values.volumes.tv.size }}
  storageClassName: local-path 
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.volumes.tv.path}}


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-torrent-tv-pv
spec:
  capacity:
    storage: {{ .Values.volumes.torrent.size }}
  storageClassName: local-path 
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.volumes.torrent.path }}/tv

---
#### prowlarr

apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr-tv-pv
spec:
  capacity:
    storage: {{ .Values.volumes.tv.size }}
  storageClassName: local-path 
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.volumes.tv.path}}

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr-torrent-tv-pv
spec:
  capacity:
    storage: {{ .Values.volumes.torrent.size }}
  storageClassName: local-path 
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.volumes.torrent.path }}/tv

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr-movies-pv
spec:
  capacity:
    storage: {{ .Values.volumes.movies.size }}
  storageClassName: local-path 
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.volumes.movies.path}}

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr-torrent-movies-pv
spec:
  capacity:
    storage: {{ .Values.volumes.torrent.size }}
  storageClassName: local-path 
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.volumes.torrent.path }}/movies

#####################################################
### CONFIG
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config-pv
spec:
  capacity:
    storage: {{ .Values.volumes.config.size }}
  storageClassName: local-path 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.volumes.config.path }}/plex

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-config-pv
spec:
  capacity:
    storage: {{ .Values.volumes.config.size }}
  storageClassName: local-path 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.volumes.config.path }}/sonarr

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-config-pv
spec:
  capacity:
    storage: {{ .Values.volumes.config.size }}
  storageClassName: local-path 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.volumes.config.path }}/radarr

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: torrent-config-pv
spec:
  capacity:
    storage: {{ .Values.volumes.config.size }}
  storageClassName: local-path 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.volumes.config.path }}/torrent

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr-config-pv
spec:
  capacity:
    storage: {{ .Values.volumes.config.size }}
  storageClassName: local-path 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.volumes.config.path }}/prowlarr

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ombi-config-pv
spec:
  capacity:
    storage: {{ .Values.volumes.config.size }}
  storageClassName: local-path 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.volumes.config.path }}/ombi

#####################################################
### TORRENT

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: torrent-movies-pv
spec:
  capacity:
    storage: {{ .Values.volumes.torrent.size }}
  storageClassName: local-path 
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.volumes.torrent.path }}/movies

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: torrent-tv-pv
spec:
  capacity:
    storage: {{ .Values.volumes.torrent.size }}
  storageClassName: local-path 
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.volumes.torrent.path }}/tv